### ISSUE TITLE
Authentication popup  before preview

### ISSUE THREAD

**Issue by ezshri** [box/box-ios-preview-sdk#1]
Hi,

I have integrated the OAuth2 in my app and am previewing the file on click. However when I click on the file I am prompted to login again before file preview for the first time.

Not sure whether it is preview-sdk problem but seems so to me.

**Comment by h2kuo** [comment]
Hi @ezshri, how are you handling authentication in your app? Are you authenticating the user through the BOXContentClient before showing the file preview controller? If not, I believe that would be the reason you are seeing the authentication controller before previewing a file.

**Comment by ezshri** [comment]
Yes. I'm authenticating the user through the BoxContentClient as I am using Content API to get all the files in my box account. What is the best way to handle this as I have to let user login on app start and then preview files ? I thought same session will be maintained across SDK's .

**Comment by h2kuo** [comment]
Yes, you are correct, the same session should be maintained across the SDKs, so you should be able to just present login on app start and not have to be prompted again. Can you provide the code you are using to authenticate, and to launch the file preview controller?

**Comment by ezshri** [comment]
Solved the problem with your suggestion. Thanks :+1:

**Comment by h2kuo** [comment]
Glad it worked for you! Feel free to open this again if you experience anymore authentication issues.
