### ISSUE TITLE
Delegate method is not getting called

### ISSUE THREAD

**Issue by siddharthsuneel** [box/box-ios-preview-sdk#10]
Delegate method willChangeToRightBarButtonItems is not getting called when preview file is of .xls or .xlsx format.

**Comment by adempsey** [comment]
@siddharthsuneel thanks for letting us know! We'll take a look and see what we find on our end. In the meantime, you should be able to work around this issue by setting the bar button items directly on the preview controller's navigation item. We'll update this thread as we look into the issue.

**Comment by sujaygarlanka** [comment]
@siddharthsuneel Sorry for the really long delay. Is this still an issue?
