### ISSUE TITLE
Bitcode error when deploying on device

### ISSUE THREAD

**Issue by ed-mejia** [box/box-ios-preview-sdk#16]
Hi I'm trying to deploy an app on a device and Xcode is reporting this:

`ld: '/Users/AppscoreDev/Documents/Apps/iOS-SolutionFinder/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(PSPDFOutlineViewController.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I'm installing the lib via pod, not sure the right path to solve this issue.

**Comment by PJSimon** [comment]
Hi @ed-mejia,

I'm going to close this old issue, assuming you've resolved this by now. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
