### ISSUE TITLE
Navigation bar issue

### ISSUE THREAD

**Issue by MohgaNabil** [box/box-ios-preview-sdk#18]
Hi 

I'm adding the BOXFilePreviewController as a child to another controller .It's working fine except that I want to hide the navigation bar . Tried the property "shouldHideBars", but it's not working and the bar keeps showing up when i tap. any ideas ?

This's how I embed the controller  :

let previewViewController = BOXFilePreviewController(contentClient: BOXContentClient.defaultClient(), file: file!)
previewViewController.view.translatesAutoresizingMaskIntoConstraints = false
previewViewController. shouldHideBars = true
self.previewContainer.addSubview(previewViewController.view)
self.addChildViewController(previewViewController)
 previewViewController.didMoveToParentViewController(self)

![simulator screen shot apr 25 2017 3 32 36 pm](https://cloud.githubusercontent.com/assets/12371520/25388347/f4467a92-29cd-11e7-8095-8f427d50b77e.png)

**Comment by irvingruan** [comment]
Hi @MohgaNabil, what is your view controller hierarchy like? Are you saying that the navigation doesn't disappear at all upon interaction? `shouldHideBars` is a property that dictates `whether the navigation bar and toolbar should be hidden on interaction`.

From the looks of it, it seems like the BOXFilePreviewController's navigation bar isn't appearing at all in your screenshot.

**Comment by MohgaNabil** [comment]
it actually disappears upon interaction, I was just wondering if I could just set the preview viewcontroller not to change the visibility of the navigation viewcontroller and thought shouldHideBars property would be the way to do so. However, I fixed it by the following : 
override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		self.navigationController?.setNavigationBarHidden(true, animated: false)
}
