### ISSUE TITLE
Issue with vide preview using shared link

### ISSUE THREAD

**Issue by MohgaNabil** [box/box-ios-preview-sdk#19]
Hi 
In this sample project [attached](https://github.com/MohgaNabil/BOXPreviewSample), I'm trying to preview a file from a sharedLink . In the application, I have a sharedLink for the file to be previewed that I use to fetch the file info using the content SDK:sharedItemInfoRequestWithSharedLinkURL and then pass the info returned to the preview viewcontroller. This works just fine with : images, pdfs, doc, ppt,xls, mp3 ,text ,etc except videos. The application halts whenever I try to preview a video with this error in the logs - not sure if it's the root cause of the issue : 

objc[43569]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1108d7998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x1126df880). One of the two will be used. Which one is undefined.

Appreciate your support, Thanks!

**Comment by MohgaNabil** [comment]
one more detail that might be resourceful, I experience this issue with .mov and .mp4 /.m4v videos with my enterprise account.

That's what happens when I try other types of videos.

![simulator screen shot may 7 2017 10 33 17 pm](https://cloud.githubusercontent.com/assets/12371520/25785047/94e694de-3377-11e7-8edc-8b52b9350346.png)
![simulator screen shot may 7 2017 10 41 22 pm](https://cloud.githubusercontent.com/assets/12371520/25785048/9533cf1a-3377-11e7-8221-3008e8d10498.png)

**Comment by jdizoglio** [comment]
In this version of the preview SDK we are not supporting shared links with password for video. We have some updates coming in our next release of the SDK to support this. This release is slated end of month. In the meantime, you can use sharedLinkCreateRequestForFileWithID.

**Comment by MohgaNabil** [comment]
Hi 
I've figured out the issue with the file info returned by the content SDK using the shared link which has no password.  The workaround I had to do is to set the canDownload flag to true and that with that the preview view controller was able to generate a preview image for the video.

Thanks for the reply though :)
