### ISSUE TITLE
fileURLForLargeThumbnailCacheEntry return nil when boxItem has a space in the title

### ISSUE THREAD

**Issue by MattKiazyk** [box/box-ios-preview-sdk#28]
Hi,

We're using `cacheLargeThumbnail` with `fileURLForLargeThumbnailCacheEntry` to be able to use the `BoxFilePreviewController` as a cache mechanism, however when a boxFile has a space in it's name, the `fileURLForLargeThumbnailCacheEntry` call return nil as it can't find it.

The file is there in the device library folder (with a space). All calls with boxFiles that have no spaces work as it should.

<img width="574" alt="screenshot 2017-11-29 13 54 41" src="https://user-images.githubusercontent.com/1119565/33396014-e3bb3326-d50c-11e7-84d2-1f56f19d5715.png">

I'm assuming `cacheThumbnail` and `fileURLForThumbnailCacheEntry` have similar issues.

v1.1.4

**Comment by PJSimon** [comment]
Hi @MattKiazyk,

I'm going to close this old issue, assuming you've resolved this by now. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
