### ISSUE TITLE
some pdf file can not preview.

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#29]
iOS/iPhone

https://ppwasdev01.boulder.ibm.com/services/lighthouse/sg/services/core/commondisplay/piwidget?sgid=155428&roleid=1
In Mobile catalog When I click on artifact BOM type Design and Delivery Artifacts, it is giving an error message. It works fine in web catalog.

**Comment by wangqiwei66** [comment]
Hi, team
Can anyone help me solve this defect? We found many pdf files can't be previed . 
And the log is following : 
2017-12-29 14:23:13.043122+0800 SGMobile[779:228328] [default] [ERROR] NSFileProviderManager used from an application or its extension (com.ibm.cio.be.ios.isg.igbs) that doesn't contain a file provider

**Comment by jlawton** [comment]
Some changes were made between v1.1.4 and v1.1.5 that are relevant to this. Could you see if the latest release fixes the issue? I don't expect it to fix the logged message for now.

**Comment by PJSimon** [comment]
Hi @wangqiwei66,

I'm going to close this old issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
