### ISSUE TITLE
Unable to run the demo box preview app

### ISSUE THREAD

**Issue by rajeshmani27** [box/box-ios-preview-sdk#3]
Hi,

I run into the following issue (pasted below) when doing the  "pod install" step to run the sample App in github repo.

Any suggestions on how to address this and get the app running would be helpful.

Thanks in advance

-----
Analyzing dependencies
Pre-downloading: `Keys` from `https://github.com/ashfurrow/empty-podspec.git`
[!] Unable to find a specification for 'Keys'.

[!] Unable to load a podspec from `Keys.podspec`, skipping:

Could not load keyring
--------

**Comment by h2kuo** [comment]
Hi @rajeshmani27, I think this is an issue with your Cocoapods setup. Are you using cocoapods-keys? It seems related to this issue: https://github.com/orta/cocoapods-keys/issues/49

**Comment by h2kuo** [comment]
Closing this for now, please feel free to re-open if you believe it is related to the SDK and not your Cocoapods setup.
