### ISSUE TITLE
Namespacing Reachability Enum

### ISSUE THREAD

**Issue by technicallyerik** [box/box-ios-preview-sdk#31]
It appears as if Reachability was recently included in a version of the Preview SDK.  It's currently defined as:

```
typedef enum : NSInteger {
	NotReachable = 0,
	ReachableViaWiFi,
	ReachableViaWWAN
} BOXNetworkStatus;
```

This can cause conflicts with other libraries that have also defined reachability statuses this way.  I would suggest to use:

```
typedef enum : NSInteger {
	BOXNotReachable = 0,
	BOXReachableViaWiFi,
	BOXReachableViaWWAN
} BOXNetworkStatus;
```

**Comment by jlawton** [comment]
Thanks for pointing this out! It looks like it's been in there for a few years, but maybe it got exposed recently.

Do you actually use the reachability code? It looks like it's never used internally to the SDK, and it is a good candidate for removal, I believe. It doesn't look like something that fits in the public interface of the SDK.

**Comment by technicallyerik** [comment]
It's not something we're using from the Box Preview SDK.  I don't think it got exposed until recently.

**Comment by jlawton** [comment]
I've removed the reachability code and the change will be in the next release.

**Comment by jlawton** [comment]
I believe this was resolved and released.
