### ISSUE TITLE
BOXPreviewCoreClient exportFileWithID not working while offline

### ISSUE THREAD

**Issue by davegreco** [box/box-ios-preview-sdk#32]
Our team is encountering an impassable and time-sensitive issue with the BoxPReviewCoreSDK framework.

As described "* Downloads and caches, then export a BOXFile. If the file is already cached, the content data will be immediately copied to the target file path." this function is supposed to immediately copy the content data to the target file path if it's already been cached, however, this error is thrown instead. It works as expected when a connection is available, this should fall back to the cache (if available) when the server is unreachable. I am certain that this file has been cached already because of the following: isFileWithIDCached returns true, I can access the file in your PSPDFKit Viewer, and if I take the device online I never get any download progress, just the immediate export of the file. The odd thing is once a file has been exported while online it will then export fine offline going forward until a new version of it has been downloaded.

Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x1c48491b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://api.box.com/2.0/files/REDACTED?fields=type%2Cid%2Csequence_id%2Cetag%2Csha1%2Cname%2Cdescription%2Csize%2Cpath_collection%2Ccreated_at%2Cmodified_at%2Ctrashed_at%2Cpurged_at%2Ccontent_created_at%2Ccontent_modified_at%2Ccreated_by%2Cmodified_by%2Cowned_by%2Cshared_link%2Cparent%2Citem_status%2Cversion_number%2Ccomment_count%2Cpermissions%2Clock%2Cextension%2Cis_package%2Chas_collaborations%2Cis_externally_owned%2Callowed_invitee_roles%2Callowed_shared_link_access_levels%2Ccollections%2Ccollection_memberships, NSErrorFailingURLKey=https://api.box.com/2.0/files/REDACTED?fields=type%2Cid%2Csequence_id%2Cetag%2Csha1%2Cname%2Cdescription%2Csize%2Cpath_collection%2Ccreated_at%2Cmodified_at%2Ctrashed_at%2Cpurged_at%2Ccontent_created_at%2Ccontent_modified_at%2Ccreated_by%2Cmodified_by%2Cowned_by%2Cshared_link%2Cparent%2Citem_status%2Cversion_number%2Ccomment_count%2Cpermissions%2Clock%2Cextension%2Cis_package%2Chas_collaborations%2Cis_externally_owned%2Callowed_invitee_roles%2Callowed_shared_link_access_levels%2Ccollections%2Ccollection_memberships, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, NSLocalizedDescription=The Internet connection appears to be offline.}

**Comment by DigitalSolomon** [comment]
I'm taking a look into this and will be in touch with you. Feel free to let me know if there are any other details you have.

**Comment by davegreco** [comment]
My apologies! I started writing this up yesterday for you and never finished when I became distracted with other matters. I hope that helps. I can reproduce this easily every time on my end as well. I have tried various BOXAssetType values, previously it was communicated to us that the library cached both a smartly chosen "preview" and the file "content" and I suspected that a decision had been made to not do that anymore at some point so when we updated the SDK this stopped working for us. We were previously just using the Cache File function that did not take an explicit type, I converted to trying this one to force "content", I believe before I was seeing it actually report download progress when asking to export the file which led me to try forcing syncing content for these files, after doing that it returned the file immediately with the caveat that I had to be online the first time that I asked to export it (which is an issue for us). I may be getting things mixed up or chasing my tail here so to say as I struggle to solve or work around the issue so take the above with a grain of salt, but it's what I appeared to have observed from when it was working previously, I'm just not 100% confident on all of it as I don't know what logic is actually behind those functions so I'm just making guesses here.

**Comment by PJSimon** [comment]
Hi @davegreco,

I'm going to close this old issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick

**Comment by davegreco** [comment]
Your team never followed through with support for our project. It ultimately was abandoned and switched to a different platform. It was so incredibly frustrating that I “can’t even”. Good luck with things, your stuff just doesn’t work and no one is able to help.
