### ISSUE TITLE
Video not playing 

### ISSUE THREAD

**Issue by sarrathy** [box/box-ios-preview-sdk#35]
I am having a enterprise account . I am not able to play video . using this sdk

**Comment by RLEE0731** [comment]
@sarrathy thanks for bringing this to our attention, can you give more context on the use case? For example what is the name of the method you're calling, how you're passing in the parameters, etc.

**Comment by Prithvijutur** [comment]
@sarrathy Do you still have this issue?

**Comment by Prithvijutur** [comment]
Closing for now, please reopen if you continue to have issues

**Comment by sarrathy** [comment]
I tried the new swift SDK . I get the following error 

{
  "error" : "Not found: File does not have representations",
  "errorType" : "BoxPreviewError",
  "message" : "Content SDK Error",
  "stackTrace" : [
    "0   BoxPreviewSDK                       0x0000000105eed333 $s13BoxPreviewSDK0aB5ErrorC7message5errorAcA0abD4EnumO_s0D0_pSgtcfc + 483",
    "1   BoxPreviewSDK                       0x0000000105eed0ed $s13BoxPreviewSDK0aB5ErrorC7message5errorAcA0abD4EnumO_s0D0_pSgtcfC + 93",
    "2   BoxPreviewSDK                       0x0000000105edcb4e $s13BoxPreviewSDK0B14ViewControllerC12downloadFile33_3A94901D68A59A86E51C979C42ECC538LLyyFys6ResultOyyt0aC00A8SDKErrorCGcfU_yycfU1_ + 334",
    "3   BoxPreviewSDK                       0x0000000105ea66dd $sIeg_IeyB_TR + 45",
    "4   libdispatch.dylib                   0x0000000109ed0dd4 _dispatch_call_block_and_release + 12",
    "5   libdispatch.dylib                   0x0000000109ed1d48 _dispatch_client_callout + 8",
    "6   libdispatch.dylib                   0x0000000109edfde6 _dispatch_main_queue_callback_4CF + 1500",
    "7   CoreFoundation                      0x000000010861cdf9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9",
    "8   CoreFoundation                      0x0000000108617a59 __CFRunLoopRun + 2329",
    "9   CoreFoundation                      0x0000000108616e16 CFRunLoopRunSpecific + 438",
    "10  GraphicsServices                    0x00000001117b0bb0 GSEventRunModal + 65",
    "11  UIKitCore                           0x000000010c0a4b48 UIApplicationMain + 1621",
    "12  BoxPreviewSampleApp                 0x0000000105b72aab main + 75",
    "13  libdyld.dylib                       0x0000000109f59c25 start + 1"
  ]
}
