### ISSUE TITLE
Disable swipe-to-dismiss gesture

### ISSUE THREAD

**Issue by technicallyerik** [box/box-ios-preview-sdk#37]
It would be great if there was a flag that we could set to disable the swipe to dismiss gesture.

**Comment by Prithvijutur** [comment]
Hi @technicallyerik  I'd like to learn more about your use case to scope this.

**Comment by technicallyerik** [comment]
@Prithvijutur -

We are presenting the preview screen modally.  You can replicate this in the demo app from the SDK by replacing line 39 with this:

```
UINavigationController *navigationWrapper = [[UINavigationController alloc] initWithRootViewController:filePreviewController];
[((UINavigationController *) self.window.rootViewController) presentViewController:navigationWrapper animated:YES completion:nil]; 
```

Now, if you zoom in and then try to pan the image, it actually dismisses the entire view.  In general, the gesture is pretty sensitive and dismisses at the slightest touch.  This ends up not being a great experience for the user.

Our current solution is to call the following in the completion block of presentViewController, but I don't think it is a great solution:

```
BOXPhotoVideoPreviewController *subVC = filePreviewController.childViewControllers[0];
[subVC.panGestureRecognizer.view removeGestureRecognizer:subVC.panGestureRecognizer];
```

**Comment by Prithvijutur** [comment]
@technicallyerik Update. Adding a way to disable pan gestures in the next release

**Comment by Prithvijutur** [comment]
Hi @technicallyerik please reopen if you have further issues

**Comment by ManasaMS85** [comment]
@Prithvijutur reopening this issue - Xcode 10.1 and ios 11 and above i am not able to access the "Previewer appearance" - it gives below error - Cannot invoke 'previewerAppearance' with an argument list of type '(for: DLFilePreviewViewController)'

The method call is : self.delegate?.previewerAppearance(for: self) and the delegate is set to BOXFilePreviewControllerDelegate

I see that their is a duplicate declaration - @property (nonatomic, readwrite, strong) BOXPreviewerAppearance *previewerAppearance; in "@interface BOXGalleryPageCell : UICollectionViewCell <BOXMediaAdapterDataSource, BOXVideoPlayerViewDelegate>
" which is creating this compile issue

**Comment by ManasaMS85** [comment]
@Prithvijutur  - We were able to make these changes and disabling of swipe works fine
