### ISSUE TITLE
The artifacts name is overlap with the back button

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#38]
In arifacts preview page, The artifacts name is overlap with the back button.
Only occured on iOS10.x , it's fine on iOS 11.x . But we have to support users on iOS10.
Because on iOS10, the back button must show a "Back" word plus a left arrow. 
How could I hide the word to avoid this issue ?

**Comment by hotechboy66** [comment]
Thanks for your advise, question is , BOXPreviewSDK provide me a hidden ViewController as : BOXFilePreviewController, So I can't do anything on this VC.

**Comment by RLEE0731** [comment]
Hi hotechboy66, BOXFilePreviewController has limited customizations you can do with regards to navigation items. It may be possible for your usage case to present BOXFilePreviewController modally, embedded in a navigation controller.

**Comment by PJSimon** [comment]
Hi @wangqiwei66,

I'm going to close this issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
