### ISSUE TITLE
Can't pass build with the introduced config.

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#39]
When I update carthage with the introduced config: 
# Box SDKs
git "git@github.com:box/box-ios-sdk.git" "master"

binary "https://github.com/box/box-ios-preview-sdk/releases/download/v1.1.5/previewSDK.json"

# 3rd Party SDKs
github "SnapKit/Masonry" ~> 1.1.0
github "jdg/MBProgressHUD" ~> 1.1.0

I found build errors happened every time . Maybe the "master" branch of box-ios-sdk is not the right config? 

Some error says can't find the class named: BOXRepresentationDimensions .

**Comment by Prithvijutur** [comment]
@wangqiwei66 Your previewSDK appears to be out of sync with the box-ios-sdk. Can you use the latest github release [here](https://github.com/box/box-ios-sdk/releases/tag/v2.0.0) and see if that fixes the issue you are having?

**Comment by wangqiwei66** [comment]
Can't fix the issue with the following: 
git "git@github.com:box/box-ios-sdk.git" "master"
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v1.1.5/previewSDK.json"
OR:
github "box/box-ios-sdk"
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v1.1.5/previewSDK.json"

Is there any other config I can use?

**Comment by LeviDahl** [comment]
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v2.0.0/previewSDK.json"

**Comment by Prithvijutur** [comment]
@wangbill66 Please use the tag or commit on the released version of box-ios-sdk and let me know if that fixes it:
github "box/box-ios-sdk" "commitHash1 or tag 2.0 release"

**Comment by PJSimon** [comment]
Hi @wangqiwei66,

I'm going to close this issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
