### ISSUE TITLE
2.0.0 built without full bitcode

### ISSUE THREAD

**Issue by BaileyM** [box/box-ios-preview-sdk#40]
When I use version 2.0.0 and try to archive, I get the following error:

`ld: bitcode bundle could not be generated because '/Users/.../Carthage/Build/iOS/BoxPreviewSDK.framework/BoxPreviewSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/.../Carthage/Build/iOS/BoxPreviewSDK.framework/BoxPreviewSDK' for architecture arm64`

**Comment by BaileyM** [comment]
I tried reverting to v.1.1.5 but I could not get that version to build properly, now after reverting to 2.0.0 I seem to be running into a similar build issue, I can no longer get it to build to device:

![screen shot 2018-10-02 at 4 55 04 pm](https://user-images.githubusercontent.com/3408797/46383216-14a22500-c664-11e8-89be-dbec26cf6f3a.png)

**Comment by BaileyM** [comment]
P.S. This is in Xcode 10.

**Comment by PJSimon** [comment]
Hi @BaileyM,

I'm going to close this issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
