### ISSUE TITLE
BOXContentClient.default().authenticate() didn't call fetchAccessToken func.

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#45]
in the elder verison, I use BOXContentClient.default().authenticate() to call the func: 
    func fetchAccessToken(completion: ((String?, Date?, Error?) -> Void)!)  in this func, I will return the accessToken and expiredDate to pass the authentication. But I found in v2.0.2 , the authenticate() didn't call this fetchAccessToken anymore. How could I adjust my process to return the BOX the accessToken to pass the authentication ??

**Comment by wangqiwei66** [comment]
Plus ,change to BOXContentClient.default().autheticateAppUser() still got no callback from fetchAccessToken. What's wrong with the usage of app user?

**Comment by boxtcarpel** [comment]
I believe you posted in a different issue (accidentally?) that you found what the problem was. https://github.com/box/box-ios-sdk/issues/580

I'm closing this issue at this point, however if you continue to have trouble, please feel free to reopen or file a new issue to reach out for help.

**Comment by wangqiwei66** [comment]
RootCause found:
1, in code, accessTokenDelegate always returns , not setted:
#pragma mark - access token delegate

    (id)accessTokenDelegate
    {
    return self.queueManager.delegate;
    }
    2, I found that after I set the delegate , client.accessTokenDelegate and queue.delegate always nil:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/23308747/50888571-f3a25a80-1430-11e9-95d2-3ffbc2c6f94e.png">

That cause the delegate func never be called.
