### ISSUE TITLE
How to view file by using file_id and access_token

### ISSUE THREAD

**Issue by knollyReddy** [box/box-ios-preview-sdk#47]
Hi Team ,
Please let us know how to work with file_id and accesstoken,
please give us the code , just we can use that code whereever i want to view box files
ex:fileID = 264541278306
accessToken = gXeWukINdTrORZIKZ2XDjKjOBPdSBF14

**Comment by knollyReddy** [comment]
Hi Team,
There is no support from you guys,
please provide the documentation for iOS to how to access the Box file by using accessToken and fileID.

Thanks,

**Comment by thuyBox** [comment]
Hi @knollyReddy, could you share your use case for using just fileID and accessToken to preview the file?

Our BOXFilePreviewController has method to show file preview given a BOXFile, e.g.:
BOXFilePreviewController *filePreviewController = [[BOXFilePreviewController alloc] initWithContentClient:[BOXContentClient defaultClient] file:file];

You can retrieve BOXFile using BOXContentClient's fileInfoRequestWithID, e.g.:
BOXFileRequest *fileRequest = [[BOXContentClient defaultClient] fileInfoRequestWithID:fileID];
fileRequest.requestAllFileFields = YES;

BOXFileBlock cacheBlock = nil;
void (^fileRequestBlock)(BOXFile *file, NSError *error) = ^(BOXFile *file, NSError *error) {
  //handle returned file
};
[fileRequest performRequestWithCached:cacheBlock refreshed:fileRequestBlock];

Thanks, let us know if you have other questions.

**Comment by PJSimon** [comment]
Hi @knollyReddy,

I'm going to close this issue, assuming you're all set. Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
