### ISSUE TITLE
BOXPreviewItem.h - modelID is set to read only

### ISSUE THREAD

**Issue by ManasaMS85** [box/box-ios-preview-sdk#48]
@property (nonatomic, readonly, strong) NSString *modelID in BOXPreviewItem.h file - which is conflicting the BOXModel - ModelID when both content sdk and box preview sdk used together in the project ;  - is set to read only and the earlier versions had it as read write . We need it as readwrite as we need to unit test and also set a local instance for other uses .

Its currently giving an build error - Cannot assign to property: 'modelID' is immutable

**Comment by jlawton** [comment]
Since `BOXPreviewItem` is a protocol, would it not be possible to cast to your concrete type to set the value?

**Comment by ManasaMS85** [comment]
@jlawton  - can you give a sample of -  cast to your concrete type . For us the problem is modelID of boxcontentsdk - "BOXFile" - > "BOXItem " ->"BOXModel"->"
/**
 *  Primary key ID of the model object.
 */
@property (nonatomic, readwrite, strong) NSString *modelID;
" 
This is shown as immutable - where as this is readwrite. 

For some reason Box - BOXPreviewItem is overriding . This part of code i am not even using in my code

**Comment by jlawton** [comment]
Yes, agreed. I'm just not sure why that would hide the previous definition in the actual type, given that you're  not using the protocol directly.

Does it go away if you add `@property (nonatomic, readwrite) NSString *modelID;` into that interface conformance? I won't be able to test this today, but knowing if that solves it will help speed up getting a fix out.

**Comment by ManasaMS85** [comment]
Hey JLawton - Yes it works placing a @property (nonatomic, readwrite) NSString *modelID in BOXItem+BOXPreviewItem.h

**Comment by ManasaMS85** [comment]
@jlawton - Any update on this it works placing a @Property (nonatomic, readwrite) NSString *modelID in BOXItem+BOXPreviewItem.h

**Comment by ManasaMS85** [comment]
@jlawton  - Did not hear any update from you - we have a release pending

**Comment by jlawton** [comment]
An update is coming. I'm not managing the release, but I believe it'll be out by tomorrow. In the meantime, the workaround should have no adverse effects.

**Comment by mattwiller** [comment]
@ManasaMS85 We just released v2.2.0 of the Preview SDK, which should include the fix for this issue.  Please give it a try and let us know if you run into any more issues!
