### ISSUE TITLE
Memory leak in SDK

### ISSUE THREAD

**Issue by ezshri** [box/box-ios-preview-sdk#5]
I got memory leak for some pdf's in pspsdfkit.  
initImageAppleJPEG : 1512 : falling back to libJPEG
initImageAppleJPEG : 1512 : falling back to libJPEG
initImageAppleJPEG : 1512 : falling back to libJPEG
initImageAppleJPEG : 1512 : falling back to libJPEG

Post this there is memory warning and the app crashes. This is a critical and high priority issue for us. Please let us know if there is any workaround available currently.

**Comment by h2kuo** [comment]
Hi @ezshri, thanks for reaching out. We haven't run into this issue ourselves yet. Could you attach one of the PDFs that the app is crashing on so that we can help troubleshoot? Thanks!

**Comment by ezshri** [comment]
Thanks ! Is there any workaround that you can think of  ?

**Comment by h2kuo** [comment]
Hi @ezshri, unfortunately we don't have a workaround available right now since we use PSPDFKit to preview all PDFs. The best thing you can do is file it with Apple on radar.apple.com so that they are aware of the issue. Please let us know if there's anything else we can do!
