### ISSUE TITLE
carthage update always timeout for box-ios-preview-sdk v2.1.0

### ISSUE THREAD

**Issue by wangqiwei66** [box/box-ios-preview-sdk#50]
When I use this config carthage : 
github "box/box-ios-sdk"
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v1.1.5/previewSDK.json" == 1.1.5
Carthage update always successed.
But changing 1.1.5 to 2.1.0:
github "box/box-ios-sdk"
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v2.1.0/previewSDK.json" == 2.1.0
Always show this:
Failed to read file or folder at /box/box-ios-preview-sdk/releases/download/v2.1.0/BoxPreviewSDK.framework.zip: Error Domain=Result.AnyError Code=1 "The request timed out."
How could I download the latest preview-sdk?

**Comment by mattwiller** [comment]
@wangqiwei66 That should work — in a sample project I set up the following Cartfile:

```
github "box/box-ios-sdk"
binary "https://github.com/box/box-ios-preview-sdk/releases/download/v2.1.0/previewSDK.json" == 2.1.0
```

It seems to be working correctly:
```shell
$ carthage update --platform iOS
*** Fetching box-ios-sdk
*** Downloading binary-only framework previewSDK at "https://github.com/box/box-ios-preview-sdk/releases/download/v2.1.0/previewSDK.json"
*** Checking out box-ios-sdk at "v2.2.0"
*** xcodebuild output can be found in /var/folders/_x/vxcqz4w52ks0tf7w3v2d26jdbqgnkz/T/carthage-xcodebuild.JnRiiz.log
*** Downloading binary-only framework previewSDK at "https://github.com/box/box-ios-preview-sdk/releases/download/v2.1.0/previewSDK.json"
*** Downloading previewSDK.framework binary at "2.1.0"
*** Building scheme "BoxContentSDK" in BoxContentSDK.xcodeproj
```

It looks like the location it's failing to read from is a local filesystem path; you may want to check your build settings.  If you run the `carthage update` command directly as I did above, does it work for you?

**Comment by PJSimon** [comment]
Hi @wangqiwei66, I'm going to close this issue, assuming you're all set.  Please feel free to re-open the issue if you still are having issues!

Thanks,
Patrick
