### ISSUE TITLE
Cannot invoke 'previewerAppearance' with an argument list of type

### ISSUE THREAD

**Issue by ManasaMS85** [box/box-ios-preview-sdk#52]
Xcode 10.1 and ios 11 and above i am not able to access the "Previewerappearance" objective c method - it gives below error - Cannot invoke 'previewerAppearance' with an argument list of type '(for: DLFilePreviewViewController)' 

The method call is : self.delegate?.previewerAppearance(for: self) and the delegate is set to BOXFilePreviewControllerDelegate

I see that their is a duplicate declaration - @Property (nonatomic, readwrite, strong) BOXPreviewerAppearance *previewerAppearance; in "@interface BOXGalleryPageCell : UICollectionViewCell <BOXMediaAdapterDataSource, BOXVideoPlayerViewDelegate>
" which is creating this compile issue

**Comment by mattwiller** [comment]
@ManasaMS85 Could you provide additional context around what you're trying to do here?  I think the duplicate declaration you mention may not be the root cause of the issue; I renamed this method in my code and it still produced the same error.  I also moved some code around in my sample app to make my application's ViewController implement `previewerAppearance()` and conform to `BOXFilePreviewControllerDelegate`, which allowed me to write this code as `self.previewerAppearance(for: previewController)` and that compiled successfully.

**Comment by ManasaMS85** [comment]
@mattwiller  - i have a class which conforms to BOXFilePreviewController and then in the same class i have self.delgate set and then i am calling the previewerapperance for the self class .
See the sample code below:

public class DLFilePreviewViewController: BOXFilePreviewController, DLLoads, DLDisplaysErrors, DLChoosesFiles {

 override public func viewDidLoad() {
        super.viewDidLoad()
        
        guard let _ = digitalLockerFile else {
            print("[File Preview] [Error] File not set.  Can not proceed.")
            customNavController?.popViewController(animated: true)
            return
        }
        self.delegate = self
        self.previewerAppearance(for: self)
        clearNavigationHeaderTitle()
        configureViews()
        showNavigationControllerNavigationBar = true
    }

I tried conforming to delegate method and passing DLFilePreviewViewController.self - none of these worked . But without any changes i can access all methods of the BOXFilePreviewControllerDelegate. Except this one

**Comment by ManasaMS85** [comment]
@mattwiller - Could you share the changes you made on the sample code

**Comment by mattwiller** [comment]
@ManasaMS85 I have something like this in my test app, which appears to work:

```swift
class ViewController: UIViewController, BOXFilePreviewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        let fetchToken: ServerAuthFetchTokenBlock = { (
            uniqueID: String?,
            fetchTokenBlockInfo: [AnyHashable: Any]?,
            completion: ((String?, Date?, Error?) -> Void)!
            ) -> Void in
            
            completion("ACCESS_TOKEN_GOES_HERE", Date(timeIntervalSinceNow: 2700), nil)
            
        }
        
        let user = ServerAuthUser(uniqueID: "UNIQUE_ID")!
        let client = BOXContentClient(for: user, initialToken: nil, fetchTokenBlockInfo: nil, fetchTokenBlock: fetchToken)!
        
        // Get file and present it
        let fileRequest = client.fileInfoRequest(withID: "FILE_ID_GOES_HERE")!
        fileRequest.perform(completion: { (file, error) in
            
            guard error == nil else {
                NSLog(error.debugDescription)
                return
            }
            
            let previewController = BOXFilePreviewController(contentClient: client, file: file)!
            previewController.delegate = self;
		
			// ---------- INTERESTING PART HERE ----------
            self.previewerAppearance(for: previewController) // <-- This compiles!
			// ---------- END INTERESTING PART ----------

            self.navigationController!.pushViewController(previewController, animated: true)
        })
    }
    
    func previewerAppearance(for controller: BOXFilePreviewController!) -> BOXPreviewerAppearance! {
        let appearance = BOXPreviewerAppearance()
        appearance.shouldAllowPanDismissal = false
        return appearance
    }
}
```

**Comment by ManasaMS85** [comment]
@mattwiller - if we have a method previewerAppearance implemented its working in our code . We can close this issue 
Thanks a lot for your support on this

**Comment by ManasaMS85** [comment]
Thanks a lot @mattwiller
