### ISSUE TITLE
BOXFilePreviewController for PDF files

### ISSUE THREAD

**Issue by subham-choudhary** [box/box-ios-preview-sdk#53]
What is the efficient way to hide the bottom bar and navigation bar title?

<img width="498" alt="screenshot 2019-02-14 at 9 07 07 pm" src="https://user-images.githubusercontent.com/33555120/52798046-2af1d000-309d-11e9-8a76-bbc0eff2ba37.png">

**Comment by mattwiller** [comment]
@subham-choudhary This part of the UI comes directly from the underlying PDF viewing library, and isn't something that can be easily customized with the Preview SDK.  There is not a direct way to hide these at this time.

**Comment by ManasaMS85** [comment]
@mattwiller - how do we hid the PDF title - if not at least we should have a way to configure it . this black text on the screen does not look appropriate 
@subham-choudhary - Please reopen this ticket
