### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by adc-jhuang** [box/box-ios-preview-sdk#8]
When building BoxPreviewSDKSampleApp, I got a long list of warnings

Xcode 7, El Capitan, with cocoapod 0.39.0:

Partial warnings shown here:

---

while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAPIOperationObserver.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UIButton
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UILabel
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UIProgressView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UISlider
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UIImageView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:@S@UIEdgeInsets
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:@S@CGRect
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:@S@CGSize
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXVideoPlayerControls.o):
warning: Could not resolve external type c:objc(cs)UIImage
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/AVFoundation-2W8OQOO5E005V.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/AVFoundation-2W8OQOO5E005V.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/JavaScriptCore-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/JavaScriptCore-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/MessageUI-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/MessageUI-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/QuartzCore-23I9VTX2KZMTH.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSMutableSet
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSDate
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSNumber
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIViewController
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSTimer
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIButton
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UILabel
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIProgressView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UISlider
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:@E@UIInterfaceOrientation
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UITableView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIImageView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UITableViewCell
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:@S@CGRect
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:@E@UIUserInterfaceIdiom
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:@S@UIEdgeInsets
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIBarButtonItem
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIEvent
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSNotification
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIView
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UIImage
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSAttributedString
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)CATransition
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)NSIndexPath
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXAudioPreviewerViewController.o):
warning: Could not resolve external type c:objc(cs)UITableViewCell
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/UIKit-1V5UHAPTOD24G.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/Darwin-38I6DLZ5IH61J.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/AVFoundation-2W8OQOO5E005V.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/AVFoundation-2W8OQOO5E005V.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/CoreGraphics-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/JavaScriptCore-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/JavaScriptCore-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/MessageUI-N94D31PLFESQ.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/MessageUI-N94D31PLFESQ.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/QuartzCore-23I9VTX2KZMTH.pcm: No object file for requested architecture
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
while processing /Projects/BoxPreviewSDKSampleApp/Pods/box-ios-preview-sdk/BoxPreviewSDK.framework/BoxPreviewSDK(BOXFilePreviewController.o):
warning: /Users/jpang/Library/Developer/Xcode/DerivedData/ModuleCache/LDBX4GY2DLBT/ObjectiveC-1RQA2RIXJIE19.pcm: No object file for requested architecture

**Comment by jlawton** [comment]
Closing, as I don't believe this is still a problem.
