### ISSUE TITLE
changing default folder

### ISSUE THREAD

**Issue by voltaire33010** [box/box-ios-preview-sdk#9]
HI
 I want to write an app that when the user log in put her in an specific folder and not the root default folder
Please can you explain if that is possible and if so how to do it
thanks a lot in advance

**Comment by boxtcarpel** [comment]
Hi @voltaire33010 
Yes, you can absolutely do that.

When using the [Browse SDK](https://github.com/box/box-ios-browse-sdk), it's as easy as setting up a [BOXFolderViewController](https://github.com/box/box-ios-browse-sdk/blob/master/BoxBrowseSDK/BoxBrowseSDK/Controllers/BOXFolderViewController.h) initialized with the folder ID or folder object of the folder you would like to start on.

Good luck and let us know if you need any additional help.

**Comment by voltaire33010** [comment]
Thanks it works !!

**Comment by boxtcarpel** [comment]
Great! Feel free to reach out again if you have any issues, or just to share how the integration is going for you!
